### ISSUE TITLE
N555 — the ratchet is mobile-only, so a rule extracted for testability can be re-inlined on web with nothing going red

### ISSUE THREAD

**Issue by dmytro-ch21** [dmytro-ch21/formspan#1032]
**Parent:** N551 (#1013, merged via #1014) extracted `pendingSuggestableIndices` into `apps/web/src/lib/api.ts` and pointed the page at it. The rule got 19 tests. **The wiring got none.**

## The measured gap

Revert ONLY the page's call site back to the inline filter — leave the extracted function and all 19 tests intact:

```diff
-  const pending = pendingSuggestableIndices(indices, sets);
+  const pending = indices.filter(
+    (i) => !sets[i]?.completed && sets[i]?.set_type !== "warmup",
+  );
```

Reproduced on this branch, 2026-09-09, against `origin/main` @ `6d834a4e`:

| check | result |
|---|---|
| `pnpm --filter web exec tsc --noEmit` | **exit 0** |
| `pnpm --filter web lint` | **exit 0** — 1 `@typescript-eslint/no-unused-vars` *warning* |
| `pnpm run test:web` | **exit 0** — 24 files, 301 tests pass |
| `pnpm run check:lint-ratchet` | **not applicable** — `MOBILE_DIR = apps/mobile`, web is out of scope |

So the #753 defect (a straight-set recommendation written into backoffs and drops) can be reinstated in one line with nothing going red. Originally spotted independently by both `ac-verifier` and `frontend-reviewer` during N551; recorded in `docs/decisions/history.md` under N551.

## Two further measurements that pick the fix

Both candidates named in N551's history entry were measured rather than assumed:

1. **A `no-restricted-syntax` / custom rule banning inline set-role filters is NOT viable as stated.** There are ~20 live `set_type` comparisons across `apps/web` and `apps/mobile`, and several are entirely legitimate — `apps/web/src/lib/api.ts:1079` and `apps/web/src/app/dashboard/sessions/[id]/page.tsx:228` both read `completed && set_type !== "warmup"`, which is the *exact shape* of the defect but is volume counting, not suggestion targeting. Nothing in the syntax distinguishes them; only the dataflow does. A ban would need a file/line allowlist, which rots.

2. **Extending the ratchet to `apps/web` surfaces ZERO pre-existing warnings** — the concern that it would is false for web. Measured live with each app's own ESLint binary:

   | app | live warnings |
   |---|---|
   | `apps/web` | **0** |
   | `apps/admin` | **8** (all `@typescript-eslint/no-unused-vars`, `_prev`/`_form` in two `content` action files) |
   | `apps/mobile` | 50 (already capped) |

3. **Mobile is already covered, web is the precise hole.** Applying the equivalent revert to `apps/mobile/app/session/[id].tsx` makes `pnpm run check:lint-ratchet` **exit 1** (`UNCAPPED: @typescript-eslint/no-unused-vars produced 1 live warning(s)`). The existing ratchet catches on mobile exactly what nothing catches on web.

## Acceptance criteria

- [ ] `scripts/check-lint-ratchet.mjs` covers `apps/web` and `apps/admin` as well as `apps/mobile`, with caps recorded PER APP (a rule cleared in one app must not be satisfiable by another app's debt).
- [ ] `apps/web` is entered at a cap of zero, so any newly-introduced warning fails rather than warns.
- [ ] `apps/admin`'s 8 pre-existing `no-unused-vars` warnings are recorded as a cap at their measured count — visible debt that cannot grow, not silence, and not a reason to block this ticket on cleaning them.
- [ ] The script's existing self-test is extended to cover the per-app aggregation, so the multi-app mechanism is proven on synthetic data before being trusted against a real run.
- [ ] **Mutation-checked:** re-applying the page revert makes the gate go red, and the report names `apps/web`. Baseline green in the same session first (a red suite is only evidence once the green one is).
- [ ] The residual is stated honestly: the ratchet catches this revert *because it leaves an unused import*. A revert that also deletes the import leaves lint clean.
- [ ] That residual is closed too — the suggestion target is type-checked at the boundary, so the brand-new `number[]` an inline filter produces is not assignable to what the apply path accepts. Mutation-checked independently: revert **and** delete the import, and `tsc` fails.
- [ ] `pnpm run verify` passes end to end.
- [ ] `docs/decisions/history.md` entry appended (before the trailing `## Open items` heading, anchored on the LAST occurrence).

Not in scope: page-level render coverage. `docs/testing/device-checks.md` records 0 of 40 web/admin pages having a test that renders them — a much larger pre-existing gap, and not this ticket.

**Comment by dmytro-ch21** [comment]
Note on the `pnpm run verify` criterion, since the review gate could not settle it at the time: `ac-verifier` reported it NOT MET after two attempts failed at `test:mobile` (`bjjSessionScreen`, `goalsScreen`) — files this branch never touches — while an unrelated concurrent `jest --maxWorkers=3` from another worktree and a live `expo run:ios` Release build were loading this shared host. Those two files passed in isolation (80/80). That is the "Colima up but contended" apparatus class, not a defect in the diff.

It has since passed **exit 0 four times** on a confirmed-clean quiescent tree (`git status --short` empty before and after each), including twice after rebasing — once onto #1031 and once onto #1033. `pre-merge-checker` independently got exit 0 as well, at 153.52s, after discarding two of its own attempts for the same contention.

CI on `c7408d3d`: `pnpm run ci:checks` reports **8 of 8 expected check runs, all passed**, exit 0 on two consecutive calls (the second confirming `mergeable` is not `CONFLICTING` — an earlier head hit exit 5 `GREEN, BUT STALE` twice as `main` moved underneath, which is why there were two rebases).

The CI log confirms the widened ratchet really runs all three apps on a runner and not only locally:

```
Lint ratchet (mobile + web + admin)  Running ESLint against apps/mobile...
Lint ratchet (mobile + web + admin)  Running ESLint against apps/web...
Lint ratchet (mobile + web + admin)  Running ESLint against apps/admin...
Lint ratchet (mobile + web + admin)  Lint ratchet: all capped rules within budget across 3 app(s).
```

Not merged — awaiting go-ahead.
